name: Lint Commit Messages
on:
  pull_request:
    branches: [develop]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - run: npm install commitlint-plugin-tense
      - uses: wagoid/commitlint-github-action@v6
        configFile: .commitlint.config.mjs
