name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "*-?v[0-9]+*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    environment: release
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: echo hello!
